import os
from os.path import isfile
import shutil
from tqdm import tqdm


def move_bad_image(bad_image_txt, destination_folder):
    """
    bad_image_txt is txt file generated by running check_bad_image.py 
    destination folder is folder you want to locate bad images
    """
    a_file = open(bad_image_txt, "r")

    list_of_paths = []
    for line in a_file:
      stripped_line = line.strip()
      list_of_paths.append(stripped_line)

    count = 0
    for line in tqdm(list_of_paths):
        # line = line[:-3]
        count += 1
        # print("Line{}: {}".format(count, line.strip()))
        partitions = line.split("/")
        new_destination = destination_folder + '/'+ partitions[-1]
        if os.path.isfile(new_destination):
          os.rename(new_destination, line)

    print(count)
    print("complete move bad images to new folder")


if __name__ == '__main__':
    bad_image_txt = "bad_images.txt"
    destination_folder = ''
    move_bad_image(bad_image_txt, destination_folder)